[phases.setup]
nixPkgs = ['python311', 'gcc', 'pkg-config']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Building Jobo AI Assistant..."']

[start]
cmd = 'uvicorn app.main:app --host 0.0.0.0 --port $PORT' 